---
title: "Case Study 6"
output: 
  html_document:
    keep_md: TRUE
    code_folding: hide
---
```{r}
library(tidyverse)
library(ggplot2)

head(diamonds)
?diamonds
summary(diamonds)

# Question 1
ggplot(data = diamonds, mapping = aes(x = x)) +
  geom_histogram(fill = "blue", color = "white") +
  labs(x = "Length In mm") +
  theme_bw()

ggplot(data = diamonds, mapping = aes(x = y)) +
  geom_histogram(fill = "blue", color = "white") +
  labs(x = "Width In mm") +
  theme_bw()

ggplot(data = diamonds, mapping = aes(x = z)) +
  geom_histogram(fill = "blue", color = "white") +
  labs(x = "Depth In mm") +
  theme_bw()

#Question 2
q2 <- ggplot(data = diamonds, mapping = aes(x = price)) +
  geom_density(fill = 'light blue', color = 'blue') +
  theme_bw()

q2


# Question 3
p1 <- ggplot(data = diamonds, mapping = aes(x = price, y = x)) +
  geom_point() +
  geom_abline(slope = 1) +
  scale_x_continuous(trans = 'log10')

p1

p2 <- ggplot(data = diamonds, mapping = aes(x = price, y = y)) +
  geom_point() +
  geom_abline(slope = 1) +
  scale_x_continuous(trans = 'log10')

p2

p3 <- ggplot(data = diamonds, mapping = aes(x = price, y = z)) +
  geom_point() +
  geom_abline(slope = 1) +
  scale_x_continuous(trans = 'log10')

p3


ggplot(data = diamonds, mapping = aes(x = cut, y = z)) +
  geom_violin(fill = 'blue', color = 'blue') +
  labs(y = 'Depth in mm') +
  theme_bw()

# Question 4
q4 <- diamonds %>% 
  select(price, carat) %>% 
  mutate(
    bin1 = case_when(
      price <= 2500 ~ "<2500",
      price <= 5000 ~ "<5000",
      price <= 7500 ~ "<7500",
      price <= 10000 ~ "<10000",
      price <= 12500 ~ "<12500",
      price <= 15000 ~ "<15000",
      price <= 17500 ~ "<17500",
      price <= 20000 ~ "<20000",
      price <= 225000 ~ "22500",
      TRUE ~ ">22500")
    )
  
  
q4

p4 <- ggplot(data = q4, mapping = aes(x = bin1, y = carat)) +
  geom_violin(fill = 'light blue', color = 'blue') +
  labs(x = "Grouped by Price") +
  theme_bw()


str = c("<2500", "<5000", "<7500", "<10000", "<12500", "<15000", "<17500", "<20000", "<22500")
q4$bin1 <- factor(q4$bin1, levels = str)

p4


# Question 5

quantile(diamonds$carat)

q5 <- diamonds %>% 
  select(price, carat) %>% 
  mutate(
    type = case_when(
      carat <= 0.4 ~ "<25",
      carat < 1.04 ~ "normal",
      carat >= 1.04 ~ ">75"
    )
  ) %>% 
  filter(type != 'normal')

q5

p5 <- ggplot(data = q5, mapping = aes(x = type, y = price)) +
  geom_violin(fill = 'light blue', color = "blue") +
  theme_bw()

p5

# Question 6
library(lattice)
p6 <- levelplot(diamonds$price ~ diamonds$cut * diamonds$carat, col.regions = rainbow(256), xlab = "Cut", ylab = "Carat")

  
p6

```
# Report
### X, Y, Z Variables
In comparing the x,y, and z variables of all the diamonds, the length (x) has the highest distrubution amongst the variables. The width and depth of the diamonds seem to be fairly similiar amonsth the diamonds

### Distribution of Price
The distribution of price is pretty much what we would expect. Most diamonds are found to be less than or equal to 5,000 dollars. Once the price gets above 10,000 dollars the amount goes way down. This is what we would expect, a gradual decline of toal diamonds as the price gets higher. What is unusual is what happens around the 4,000 dollar range.

### Most Important Variable Related to Price
I found that depth (z) is the most important variable in relation to price, because as the depth goes up, so does the price of the diamond. It is the closest to a 1:1 ratio. In relation to cut, depth is fairly consistent in regards to how the diamond is graded. It allows for lower quality diamonds to be more expensive because often the depth is good enough in the diamond enough for the price to go up even if the cut isnt above good.

### Carat Partitioned by Price
The graphic made for this shows that as the carat goes up, so does the price of the diamond. This is what we would expect from the data.

### Large Diamonds vs. Small Diamonds
You can see by the graphic that the bottom 25% of diamonds based on carat size is consitantly priced below 2,500 dollars. Also, the top 75% of diamonds based on carat size has varying prices that are much higher. This is what we would exect from the data, the larger the data, the higher the price is.

### Cut, Carat, and Price
This graphic shows that as the cut goes from Fairly Good to Ideal and the carat size increases the price goes up as well. What is interesting is that the most expensive diamonds are in the fair category but with the highest carat size. This means that the largest factor in price isnt cut but carat size. The larger the diamond the more expensice it is.
